# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
#relative_permalinks: true

# Setup
title:            Matthias Claassen
tagline:          'Portfolio & Devlogs'
description:      'Portfolio & Devlogs'
url:              http://mwclaass.github.io
baseurl:          /

author:
  name:           'Matthias Claassen'
  url:            https://mwclaass.github.io

gems:             [jekyll-paginate]
paginate:         5
paginate_path:    '/devlogs/page:num'

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/mwclaass
